### ISSUE TITLE
Error when create checkpoint from artifact builded on image

### ISSUE THREAD

**Issue by fwborges** [CRaC/openjdk-builds#5]
Hi again!

I'm trying build project with maven in Dockerfile and when I try create a checkpoint, this exception comes:

```
An exception during a checkpoint operation:
jdk.crac.CheckpointException
        at java.base/jdk.crac.Core.checkpointRestore1(Core.java:141)
        at java.base/jdk.crac.Core.checkpointRestore(Core.java:246)
        at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:262)
        Suppressed: jdk.crac.impl.CheckpointOpenSocketException: tcp localAddr 0.0.0.0 localPort 5000 remoteAddr 0.0.0.0 remotePort 0
                at java.base/jdk.crac.Core.translateJVMExceptions(Core.java:91)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:145)
                ... 2 more
        Suppressed: jdk.crac.impl.CheckpointOpenSocketException: tcp localAddr 0.0.0.0 localPort 9090 remoteAddr 0.0.0.0 remotePort 0
                at java.base/jdk.crac.Core.translateJVMExceptions(Core.java:91)
                at java.base/jdk.crac.Core.checkpointRestore1(Core.java:145)
``` 

My Dockerfile

```
FROM ubuntu:20.04
RUN mkdir /src
COPY . /src
WORKDIR /src
RUN apt-get update -y
RUN apt-get install maven -y
RUN mvn --settings /src/settings.xml clean install

RUN mkdir /app
COPY /src/target/*.jar /app/app.jar

RUN mkdir /opt/crac-files

ENV JAVA_HOME /opt/jdk
ENV PATH $JAVA_HOME/bin:$PATH
ADD "https://github.com/CRaC/openjdk-builds/releases/download/17-crac%2B5/openjdk-17-crac+5_linux-x64.tar.gz" $JAVA_HOME/openjdk.tar.gz
RUN tar --extract --file $JAVA_HOME/openjdk.tar.gz --directory "$JAVA_HOME" --strip-components 1; rm $JAVA_HOME/openjdk.tar.gz;

EXPOSE 5000 9090
``` 

When I built the project on host and copy jar to container in Dockerfile, the checkpoint works.
Thanks!

**Comment by AntonKozlov** [comment]
Hi, sorry for the late reply. From the log it looks that the app just had open sockets, apparently from the app that was not adjusted for CRaC.
